version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
# dùng để tự động cập nhật các phần mềm và các thư viện phụ thuộc trong dự án